#!/bin/bash
set -e

ipset flush "$1"

# If installed, aggregate will merge overlapping IP ranges, compressing the generated ipset
PROCESS="aggregate"
if ! which $PROCESS &>/dev/null
then
	PROCESS="cat -"
fi

cat db/* | $PROCESS | while read ip
do
	ipset add "$1" "$ip"
done

echo "Done loading $(sudo ipset list $1 | wc -l) entries"
