#!/bin/sh
# xssh: Opens a ssh session with X and PulseAudio forwarding.

# The port under which the local pulseaudio instance is listening
PULSE_PORT=4713
HOST_CONF= "~/.config/xssh-host"

if [ -n "$1" ]
then
	HOST="$1"
	echo "$1" > "$HOST_CONF"
elif [ -f "$HOST_CONF" ]
then
	HOST="$(cat "$HOST_CONF")"
else
	echo "xssh: Hostname required"
	exit 1
fi

if (nmap -p $PULSE_PORT localhost | grep -q "tcp *open")
then
	ssh -C -X -R 4714:localhost:$PULSE_PORT -t "$HOST" "pax11publish -S tcp:localhost:4714 -e; bash -l"
else
	echo "xssh: The local port $PULSE_PORT needs to be open. Check 'Network Server' settings in paprefs and restart pulseaudio"
fi
